version: '3.8'

services:

  app:
    volumes:
      - ./:/app
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    networks:
      - app-network
      # gunicorn --workers $((KERNEL_AMOUNTS*2+1)) -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8000
      # uvicorn app.main:app --host 0.0.0.0 --port 8000
    command: >
      bash -c " 
      alembic upgrade head && 
      KERNEL_AMOUNTS=$(nproc) &&  
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_OUTER_PORT}:${POSTGRES_INNER_PORT}
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network
    ports:
      - ${REDIS_OUTER_PORT}:${REDIS_INNER_PORT}

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
