"""added indexes

Revision ID: 06066a24d571
Revises: 19f3bc5d70b1
Create Date: 2024-12-04 19:59:33.464319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06066a24d571'
down_revision: Union[str, None] = '19f3bc5d70b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_category_category_id', 'category', ['category_id'], unique=False)
    op.create_index('idx_course_category_id', 'course', ['category_id'], unique=False)
    op.create_index('idx_course_course_id', 'course', ['course_id'], unique=False)
    op.create_index('idx_course_instructor_id', 'course', ['instructor_id'], unique=False)
    op.create_index('idx_instructor_instructor_id', 'instructors', ['instructor_id'], unique=False)
    op.create_index('idx_instructor_user_id', 'instructors', ['user_id'], unique=False)
    op.create_index('idx_lesson_tasks_lesson_id', 'lesson_tasks', ['lesson_id'], unique=False)
    op.create_index('idx_lesson_tasks_lesson_task_id', 'lesson_tasks', ['lesson_task_id'], unique=False)
    op.create_index('idx_lessons_course_id', 'lessons', ['course_id'], unique=False)
    op.create_index('idx_lessons_lesson_id', 'lessons', ['lesson_id'], unique=False)
    op.create_index('idx_student_course_course_id', 'student_course', ['course_id'], unique=False)
    op.create_index('idx_student_course_student_id', 'student_course', ['student_id'], unique=False)
    op.create_index('idx_student_lesson_lesson_id', 'student_lesson', ['lesson_id'], unique=False)
    op.create_index('idx_student_lesson_student_id', 'student_lesson', ['student_id'], unique=False)
    op.create_index('idx_student_lesson_task_lesson_task_id', 'student_lesson_task', ['lesson_task_id'], unique=False)
    op.create_index('idx_student_student_id', 'students', ['student_id'], unique=False)
    op.create_index('idx_student_user_id', 'students', ['user_id'], unique=False)
    op.create_index('idx_user_id', 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id', table_name='users')
    op.drop_index('idx_student_user_id', table_name='students')
    op.drop_index('idx_student_student_id', table_name='students')
    op.drop_index('idx_student_lesson_task_lesson_task_id', table_name='student_lesson_task')
    op.drop_index('idx_student_lesson_student_id', table_name='student_lesson')
    op.drop_index('idx_student_lesson_lesson_id', table_name='student_lesson')
    op.drop_index('idx_student_course_student_id', table_name='student_course')
    op.drop_index('idx_student_course_course_id', table_name='student_course')
    op.drop_index('idx_lessons_lesson_id', table_name='lessons')
    op.drop_index('idx_lessons_course_id', table_name='lessons')
    op.drop_index('idx_lesson_tasks_lesson_task_id', table_name='lesson_tasks')
    op.drop_index('idx_lesson_tasks_lesson_id', table_name='lesson_tasks')
    op.drop_index('idx_instructor_user_id', table_name='instructors')
    op.drop_index('idx_instructor_instructor_id', table_name='instructors')
    op.drop_index('idx_course_instructor_id', table_name='course')
    op.drop_index('idx_course_course_id', table_name='course')
    op.drop_index('idx_course_category_id', table_name='course')
    op.drop_index('idx_category_category_id', table_name='category')
    # ### end Alembic commands ###
