"""Initial migration

Revision ID: 9167ea57908f
Revises: 
Create Date: 2024-12-04 17:57:10.139531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9167ea57908f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('second_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('active', 'inactive', 'admin', name='roles'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('instructors',
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('academic_degree', sa.Enum('bachelor', 'master', 'doctorate', name='academicdegree'), nullable=True),
    sa.Column('academical_experience', sa.Integer(), nullable=True),
    sa.Column('H_index', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('instructor_id')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subscription_plan', sa.Enum('free', 'premium', 'trial', name='subscriptionplan'), nullable=True),
    sa.Column('learning_style', sa.Enum('visual', 'auditory', name='learningstyle'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('instructors')
    op.drop_table('users')
    # ### end Alembic commands ###
